"""empty message

Revision ID: 0ec40831769e
Revises: 
Create Date: 2020-04-06 15:26:37.416728

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0ec40831769e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("balances_wallet_id_fkey", "balances", type_="foreignkey")
    op.create_foreign_key(None, "balances", "wallets", ["wallet_id"], ["id"])
    op.add_column("orders", sa.Column("currency", sa.String(length=50), nullable=False))
    op.add_column("orders", sa.Column("fee", sa.Float(), nullable=False))
    op.add_column("orders", sa.Column("filled_qty", sa.Float(), nullable=False))
    op.add_column("orders", sa.Column("unfulfilled_qty", sa.Float(), nullable=False))
    op.drop_column("orders", "leaves_qty")
    op.drop_column("orders", "cum_qty")
    op.add_column("trades", sa.Column("currency", sa.String(length=50), nullable=False))
    op.add_column("trades", sa.Column("trade_fee", sa.Float(), nullable=False))
    op.add_column("transactions", sa.Column("tx_type", sa.String(), nullable=True))
    op.drop_constraint(
        "transactions_wallet_id_fkey", "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "wallet_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("wallet_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "transactions_wallet_id_fkey", "transactions", "wallets", ["wallet_id"], ["id"]
    )
    op.drop_column("transactions", "tx_type")
    op.drop_column("trades", "trade_fee")
    op.drop_column("trades", "currency")
    op.add_column(
        "orders",
        sa.Column(
            "cum_qty",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "leaves_qty",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("orders", "unfulfilled_qty")
    op.drop_column("orders", "filled_qty")
    op.drop_column("orders", "fee")
    op.drop_column("orders", "currency")
    op.drop_constraint(None, "balances", type_="foreignkey")
    op.create_foreign_key(
        "balances_wallet_id_fkey", "balances", "balances", ["wallet_id"], ["id"]
    )
    # ### end Alembic commands ###
