version: '3.5'

services:
  api:
    image: iroha_db_api
    network_mode: host
    container_name: iroha-db-api
    depends_on:
      - db
  worker:
    image: iroha_db_api
    network_mode: host
    container_name: iroha-db-worker
    depends_on:
      - db
  db:
    image: postgres
    container_name: iroha-block-db
    volumes: 
      - iroha-db-block-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${API_DB_USER}
      - POSTGRES_USER=${API_DB_USER}
      - POSTGRES_DB=${API_DB}
    network_mode: host
    ports:
    - "${API_DB_PORT}:${API_DB_PORT}"
    logging:
      driver: none
    command: -p ${API_DB_PORT}

volumes:
  iroha-db-block-data: