[tool.poetry]
name = "iroha_blocks_api"
version = "0.1.0"
description = "Hyperleder Iroha V1 Block Explorer REST API"
authors = ["Farren Jackson <farren@itbsoftware.co.za>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = "^1.3.19"
iroha = "^0.0.5"
psycopg2 = "^2.8.5"
pandas = "^1.1.1"
psycopg2-binary = "^2.8.5"
huey = "^2.3.0"
gevent = "^20.6.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
bandit = "^1.6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
